apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-dep
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-container
        image: auth-img:0.0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 8000


---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - port: 8000           # Port cible pour le conteneur
      targetPort: 8000      # Port exposé par le conteneur
      nodePort: 30001       # Port NodePort pour accéder au service
